version: "3"

services:
  api:
    container_name: image_repo_api
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 5001
    volumes:
      - ".:/home/node/app"
      - "./docker/run.sh:/usr/bin/run.sh"
    depends_on:
      - mongo
    environment:
      NODE_ENV: 'development'
      PORT: 5001
      DB_USERNAME: 'api_user'
      DB_PASSWORD: 'c3VwZXJfc2VjcmV0Cg=='
      DB_NAME: 'db_api'
      DB_HOSTNAME: image_repo_mongo
      DB_PORT: 27017
      JWT_SECRET: 'do a better job of hiding this please'
    networks:
      - image_repo_network

  mongo:
    image: mongo:4.2
    container_name: image_repo_mongo
    ports:
      - 27017
    volumes:
      - "./docker/.data/mongo:/var/lib/mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api_user
      - MONGO_INITDB_ROOT_PASSWORD=c3VwZXJfc2VjcmV0Cg==
      - MONGO_INITDB_DATABASE=db_api
    networks:
      - image_repo_network

networks:
  image_repo_network:
